"""
Alias manager.
Creates a named command (default: `claude-local`) that runs Claude Code
pointed at a local Ollama backend instead of the Anthropic cloud.

Architecture
────────────
  claude-local [args]
      └─> wrapper script
              ├─ ensures `ollama serve` is running
              ├─ ensures litellm proxy is up on PROXY_PORT
              │    litellm exposes an Anthropic-compatible /v1/messages endpoint
              │    backed by the chosen Ollama model
              └─> ANTHROPIC_BASE_URL=http://localhost:PROXY_PORT
                  ANTHROPIC_API_KEY=local-key
                  claude [args]

The wrapper is installed to ~/.local/bin/ (Linux/macOS) or
%USERPROFILE%/AppData/Local/Programs/claude-setup/ (Windows),
and the directory is added to PATH in the shell profile if needed.
"""

import os
import platform
import shutil
import stat
import subprocess
from dataclasses import dataclass, field
from typing import Callable, List, Optional


DEFAULT_ALIAS    = "claude-local"
PROXY_PORT       = 4001          # litellm Anthropic-compat proxy port
PROXY_WAIT_SECS  = 2             # seconds to wait after spawning proxy


# ── Wrapper templates ─────────────────────────────────────────────────────────

# Unix shell wrapper (bash)
_UNIX_WRAPPER = """\
#!/usr/bin/env bash
# claude-local — Claude Code routed through a local Ollama model
# Generated by claude-code-setup  (do not edit manually)
#
# Cloud alias  : claude          → Anthropic API
# Local alias  : {alias_name}   → Ollama / {model_id}  (via litellm proxy)

set -euo pipefail

ALIAS_NAME="{alias_name}"
MODEL_ID="{model_id}"
PROXY_PORT={proxy_port}
PROXY_WAIT={proxy_wait}

# ── helpers ──────────────────────────────────────────────────────────────────
_port_in_use() {{
  lsof -ti tcp:"$1" &>/dev/null 2>&1 || ss -tlnp 2>/dev/null | grep -q ":$1 "
}}

_log() {{ echo "[$ALIAS_NAME] $*" >&2; }}

# ── 1. Ensure Ollama is running ───────────────────────────────────────────────
if ! pgrep -x ollama &>/dev/null; then
  _log "Starting Ollama in the background..."
  nohup ollama serve &>/dev/null &
  sleep 1
fi

# ── 2. Ensure litellm proxy is running ───────────────────────────────────────
if ! _port_in_use "$PROXY_PORT"; then
  if ! command -v litellm &>/dev/null; then
    echo "[$ALIAS_NAME] ERROR: litellm is not installed."
    echo "  Install it with:  pip install litellm"
    exit 1
  fi
  _log "Starting litellm proxy on port $PROXY_PORT (model: $MODEL_ID)..."
  nohup litellm \\
    --model "ollama/$MODEL_ID" \\
    --port "$PROXY_PORT" \\
    --drop_params \\
    &>/tmp/litellm-claude-local.log &
  sleep "$PROXY_WAIT"
fi

# ── 3. Run Claude Code via local proxy ───────────────────────────────────────
export ANTHROPIC_BASE_URL="http://localhost:$PROXY_PORT"
export ANTHROPIC_API_KEY="local-key"
exec claude "$@"
"""

# Windows .cmd wrapper
_WIN_WRAPPER = """\
@echo off
REM claude-local — Claude Code routed through a local Ollama model
REM Generated by claude-code-setup  (do not edit manually)
REM
REM Cloud alias  : claude          -> Anthropic API
REM Local alias  : {alias_name}   -> Ollama / {model_id}  (via litellm proxy)

SET ALIAS_NAME={alias_name}
SET MODEL_ID={model_id}
SET PROXY_PORT={proxy_port}

REM Check if litellm is available
where litellm >nul 2>&1
IF ERRORLEVEL 1 (
    echo [%ALIAS_NAME%] ERROR: litellm is not installed.
    echo   Install it with:  pip install litellm
    exit /b 1
)

REM Check if proxy is already running on the port
netstat -an | find ":%PROXY_PORT% " | find "LISTENING" >nul 2>&1
IF ERRORLEVEL 1 (
    echo [%ALIAS_NAME%] Starting litellm proxy on port %PROXY_PORT%...
    start /B litellm --model ollama/%MODEL_ID% --port %PROXY_PORT% --drop_params >nul 2>&1
    timeout /t {proxy_wait} /nobreak >nul
)

REM Run Claude Code via local proxy
SET ANTHROPIC_BASE_URL=http://localhost:%PROXY_PORT%
SET ANTHROPIC_API_KEY=local-key
claude %*
"""


@dataclass
class AliasInfo:
    alias_name: str
    model_id: str
    proxy_port: int
    wrapper_path: str
    bin_dir: str


@dataclass
class AliasStatus:
    alias_name: str
    wrapper_path: str
    model_id: str
    proxy_port: int
    on_path: bool


class AliasManager:
    """
    Creates and manages `claude-local` (or custom-named) wrapper commands
    that proxy Claude Code through a local Ollama model.
    """

    def __init__(self, on_log: Callable[[str], None] = None):
        self.log = on_log or print

    # ── Public API ────────────────────────────────────────────────────────────

    def create(
        self,
        alias_name: str = DEFAULT_ALIAS,
        model_id: str = "qwen2.5-coder:7b",
        proxy_port: int = PROXY_PORT,
    ) -> Optional[AliasInfo]:
        """
        Generate and install a wrapper script.
        Returns AliasInfo on success, None on failure.
        """
        bin_dir = self._bin_dir()
        os.makedirs(bin_dir, exist_ok=True)

        wrapper_path = self._wrapper_path(bin_dir, alias_name)
        self._write_wrapper(wrapper_path, alias_name, model_id, proxy_port)

        self._ensure_on_path(bin_dir)

        self.log(f"  Alias '{alias_name}' created at {wrapper_path}")
        self.log(f"  Model: {model_id}  |  Proxy port: {proxy_port}")
        return AliasInfo(
            alias_name=alias_name,
            model_id=model_id,
            proxy_port=proxy_port,
            wrapper_path=wrapper_path,
            bin_dir=bin_dir,
        )

    def remove(self, alias_name: str = DEFAULT_ALIAS) -> bool:
        """Delete the wrapper script for the given alias."""
        bin_dir = self._bin_dir()
        wrapper_path = self._wrapper_path(bin_dir, alias_name)
        if os.path.isfile(wrapper_path):
            os.remove(wrapper_path)
            self.log(f"  Alias '{alias_name}' removed ({wrapper_path})")
            return True
        self.log(f"  [warn] Alias '{alias_name}' not found at {wrapper_path}")
        return False

    def list_aliases(self) -> List[AliasStatus]:
        """Scan the bin dir and return all claude-* wrappers created by this tool."""
        bin_dir = self._bin_dir()
        aliases = []
        if not os.path.isdir(bin_dir):
            return aliases

        for fname in sorted(os.listdir(bin_dir)):
            fpath = os.path.join(bin_dir, fname)
            if not os.path.isfile(fpath):
                continue
            try:
                with open(fpath) as f:
                    content = f.read()
            except (IOError, UnicodeDecodeError):
                continue
            if "Generated by claude-code-setup" not in content:
                continue
            model_id  = self._extract_value(content, "MODEL_ID")
            port_str  = self._extract_value(content, "PROXY_PORT")
            aliases.append(AliasStatus(
                alias_name=fname.removesuffix(".cmd"),
                wrapper_path=fpath,
                model_id=model_id or "unknown",
                proxy_port=int(port_str) if port_str and port_str.isdigit() else PROXY_PORT,
                on_path=shutil.which(fname.removesuffix(".cmd")) is not None,
            ))
        return aliases

    def check_litellm(self) -> bool:
        """Return True if litellm is installed."""
        return shutil.which("litellm") is not None

    def install_litellm(self) -> bool:
        """pip-install litellm[proxy]. Returns True on success."""
        self.log("Installing litellm[proxy] via pip...")
        python = shutil.which("python3") or shutil.which("python")
        if not python:
            self.log("[error] Python not found.")
            return False
        try:
            result = subprocess.run(
                [python, "-m", "pip", "install", "--quiet", "litellm[proxy]"],
                timeout=180,
                capture_output=True,
                text=True,
            )
            if result.returncode == 0:
                self.log("  litellm installed.")
                return True
            self.log(f"  [error] pip install failed: {result.stderr.strip()}")
        except (subprocess.TimeoutExpired, FileNotFoundError):
            self.log("  [error] pip install timed out or failed.")
        return False

    # ── Internals ─────────────────────────────────────────────────────────────

    def _bin_dir(self) -> str:
        system = platform.system()
        if system == "Windows":
            return os.path.join(
                os.environ.get("USERPROFILE", os.path.expanduser("~")),
                "AppData", "Local", "Programs", "claude-setup",
            )
        # macOS / Linux — prefer ~/.local/bin (XDG standard)
        return os.path.join(os.path.expanduser("~"), ".local", "bin")

    def _wrapper_path(self, bin_dir: str, alias_name: str) -> str:
        if platform.system() == "Windows":
            return os.path.join(bin_dir, f"{alias_name}.cmd")
        return os.path.join(bin_dir, alias_name)

    def _write_wrapper(
        self, path: str, alias_name: str, model_id: str, proxy_port: int
    ):
        if platform.system() == "Windows":
            content = _WIN_WRAPPER.format(
                alias_name=alias_name,
                model_id=model_id,
                proxy_port=proxy_port,
                proxy_wait=PROXY_WAIT_SECS,
            )
        else:
            content = _UNIX_WRAPPER.format(
                alias_name=alias_name,
                model_id=model_id,
                proxy_port=proxy_port,
                proxy_wait=PROXY_WAIT_SECS,
            )
        with open(path, "w") as f:
            f.write(content)
        if platform.system() != "Windows":
            # Make executable
            st = os.stat(path)
            os.chmod(path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    def _ensure_on_path(self, bin_dir: str):
        """Add bin_dir to PATH in the shell profile if it isn't already there."""
        if platform.system() == "Windows":
            self._ensure_on_path_windows(bin_dir)
            return

        profile = self._shell_profile()
        if not profile:
            self.log(f"  [warn] Could not detect shell profile. Add {bin_dir} to PATH manually.")
            return

        try:
            with open(profile) as f:
                content = f.read()
        except FileNotFoundError:
            content = ""

        if bin_dir in content:
            return  # already present

        snippet = f'\nexport PATH="{bin_dir}:$PATH"\n'
        with open(profile, "a") as f:
            f.write(snippet)
        self.log(f"  Added {bin_dir} to PATH in {profile}")
        self.log(f"  Run `source {profile}` or open a new terminal to activate.")

    def _ensure_on_path_windows(self, bin_dir: str):
        """Add bin_dir to the user PATH on Windows via setx."""
        try:
            current = os.environ.get("PATH", "")
            if bin_dir.lower() in current.lower():
                return
            subprocess.run(
                ["setx", "PATH", f"{bin_dir};{current}"],
                capture_output=True, timeout=10,
            )
            self.log(f"  Added {bin_dir} to user PATH (restart terminal to apply).")
        except (subprocess.TimeoutExpired, FileNotFoundError):
            self.log(f"  [warn] Could not set PATH automatically. Add {bin_dir} manually.")

    def _shell_profile(self) -> Optional[str]:
        shell = os.environ.get("SHELL", "")
        if "zsh" in shell:
            for p in ("~/.zshrc", "~/.zprofile"):
                path = os.path.expanduser(p)
                if os.path.isfile(path):
                    return path
            return os.path.expanduser("~/.zshrc")
        if "fish" in shell:
            conf = os.path.expanduser("~/.config/fish/config.fish")
            os.makedirs(os.path.dirname(conf), exist_ok=True)
            return conf
        for p in ("~/.bashrc", "~/.bash_profile", "~/.profile"):
            path = os.path.expanduser(p)
            if os.path.isfile(path):
                return path
        return os.path.expanduser("~/.bashrc")

    @staticmethod
    def _extract_value(content: str, key: str) -> Optional[str]:
        """Extract VALUE from lines like  KEY="VALUE"  or  SET KEY=VALUE."""
        import re
        match = re.search(rf'{key}[=:]\s*["\']?([^\s"\'\\]+)', content)
        return match.group(1) if match else None
