"""
Alias manager.
Creates a named command (default: `claude-local`) that runs Claude Code
pointed at a local Ollama backend instead of the Anthropic cloud.

Architecture
────────────
  claude-local [args]
      └─> wrapper script
              ├─ ensures `ollama serve` is running
              └─> ANTHROPIC_BASE_URL=http://localhost:11434
                  ANTHROPIC_API_KEY=ollama
                  claude --model <model_id> [args]

Ollama exposes a native Anthropic-compatible /v1/messages endpoint,
so Claude Code connects directly — no Python packages, no proxy process.

See: https://docs.ollama.com/integrations/claude-code

The wrapper is installed to ~/.local/bin/ (Linux/macOS) or
%USERPROFILE%/AppData/Local/Programs/claude-setup/ (Windows),
and the directory is added to PATH in the shell profile if needed.
"""

import os
import platform
import shutil
import stat
import subprocess
from dataclasses import dataclass
from typing import Callable, List, Optional


DEFAULT_ALIAS   = "claude-local"
OLLAMA_PORT     = 11434
OLLAMA_BASE_URL = f"http://localhost:{OLLAMA_PORT}"


# ── Wrapper templates ─────────────────────────────────────────────────────────

# Unix shell wrapper (bash)
_UNIX_WRAPPER = """\
#!/usr/bin/env bash
# {alias_name} — Claude Code routed directly through Ollama
# Generated by claude-code-setup  (do not edit manually)
#
# How it works:
#   Ollama exposes a native Anthropic-compatible API at http://localhost:11434
#   Claude Code connects directly — no proxy or extra packages needed.
#   See https://docs.ollama.com/integrations/claude-code
#
# Cloud alias  : claude          → Anthropic API  (unchanged)
# Local alias  : {alias_name}   → Ollama / {model_id}  (direct, no proxy)

set -euo pipefail

ALIAS_NAME="{alias_name}"
MODEL_ID="{model_id}"
OLLAMA_URL="{ollama_url}"

_log() {{ echo "[$ALIAS_NAME] $*" >&2; }}

# ── 1. Check Ollama is installed ─────────────────────────────────────────────
if ! command -v ollama &>/dev/null; then
  echo "[$ALIAS_NAME] ERROR: Ollama is not installed."
  echo "  Install it from: https://ollama.ai"
  exit 1
fi

# ── 2. Ensure Ollama is running ───────────────────────────────────────────────
if ! pgrep -x ollama &>/dev/null; then
  _log "Starting Ollama in the background..."
  nohup ollama serve &>/dev/null &
  sleep 2
fi

# ── 3. Run Claude Code directly via Ollama's Anthropic-compatible API ─────────
export ANTHROPIC_BASE_URL="$OLLAMA_URL"
export ANTHROPIC_API_KEY="ollama"
exec claude --model "$MODEL_ID" "$@"
"""

# Windows .cmd wrapper
_WIN_WRAPPER = """\
@echo off
REM {alias_name} — Claude Code routed directly through Ollama
REM Generated by claude-code-setup  (do not edit manually)
REM
REM How it works:
REM   Ollama exposes a native Anthropic-compatible API at http://localhost:11434
REM   Claude Code connects directly - no proxy or extra packages needed.
REM   See https://docs.ollama.com/integrations/claude-code
REM
REM Cloud alias  : claude          -> Anthropic API  (unchanged)
REM Local alias  : {alias_name}   -> Ollama / {model_id}  (direct, no proxy)

SET ALIAS_NAME={alias_name}
SET MODEL_ID={model_id}
SET OLLAMA_URL={ollama_url}

REM Check Ollama is installed
where ollama >nul 2>&1
IF ERRORLEVEL 1 (
    echo [%ALIAS_NAME%] ERROR: Ollama is not installed.
    echo   Install it from: https://ollama.ai
    exit /b 1
)

REM Run Claude Code directly via Ollama's Anthropic-compatible API
SET ANTHROPIC_BASE_URL=%OLLAMA_URL%
SET ANTHROPIC_API_KEY=ollama
claude --model %MODEL_ID% %*
"""


@dataclass
class AliasInfo:
    alias_name: str
    model_id: str
    ollama_url: str
    wrapper_path: str
    bin_dir: str


@dataclass
class AliasStatus:
    alias_name: str
    wrapper_path: str
    model_id: str
    ollama_url: str
    on_path: bool


class AliasManager:
    """
    Creates and manages `claude-local` (or custom-named) wrapper commands
    that connect Claude Code directly to a local Ollama instance.

    Uses Ollama's native Anthropic-compatible API — no proxy, no extra packages.
    """

    def __init__(self, on_log: Callable[[str], None] = None):
        self.log = on_log or print

    # ── Public API ────────────────────────────────────────────────────────────

    def create(
        self,
        alias_name: str = DEFAULT_ALIAS,
        model_id: str = "qwen2.5-coder:7b",
        ollama_url: str = OLLAMA_BASE_URL,
    ) -> Optional[AliasInfo]:
        """
        Generate and install a wrapper script.
        Returns AliasInfo on success, None on failure.
        """
        bin_dir = self._bin_dir()
        os.makedirs(bin_dir, exist_ok=True)

        wrapper_path = self._wrapper_path(bin_dir, alias_name)
        self._write_wrapper(wrapper_path, alias_name, model_id, ollama_url)

        self._ensure_on_path(bin_dir)

        self.log(f"  Alias '{alias_name}' created at {wrapper_path}")
        self.log(f"  Model: {model_id}  |  Ollama: {ollama_url}")
        return AliasInfo(
            alias_name=alias_name,
            model_id=model_id,
            ollama_url=ollama_url,
            wrapper_path=wrapper_path,
            bin_dir=bin_dir,
        )

    def remove(self, alias_name: str = DEFAULT_ALIAS) -> bool:
        """Delete the wrapper script for the given alias."""
        bin_dir = self._bin_dir()
        wrapper_path = self._wrapper_path(bin_dir, alias_name)
        if os.path.isfile(wrapper_path):
            os.remove(wrapper_path)
            self.log(f"  Alias '{alias_name}' removed ({wrapper_path})")
            return True
        self.log(f"  [warn] Alias '{alias_name}' not found at {wrapper_path}")
        return False

    def list_aliases(self) -> List[AliasStatus]:
        """Scan the bin dir and return all wrappers created by this tool."""
        bin_dir = self._bin_dir()
        aliases = []
        if not os.path.isdir(bin_dir):
            return aliases

        for fname in sorted(os.listdir(bin_dir)):
            fpath = os.path.join(bin_dir, fname)
            if not os.path.isfile(fpath):
                continue
            try:
                with open(fpath) as f:
                    content = f.read()
            except (IOError, UnicodeDecodeError):
                continue
            if "Generated by claude-code-setup" not in content:
                continue
            model_id   = self._extract_value(content, "MODEL_ID")
            ollama_url = self._extract_value(content, "OLLAMA_URL") or OLLAMA_BASE_URL
            aliases.append(AliasStatus(
                alias_name=fname.removesuffix(".cmd"),
                wrapper_path=fpath,
                model_id=model_id or "unknown",
                ollama_url=ollama_url,
                on_path=shutil.which(fname.removesuffix(".cmd")) is not None,
            ))
        return aliases

    def check_ollama(self) -> bool:
        """Return True if Ollama is installed and on PATH."""
        return shutil.which("ollama") is not None

    def check_node(self) -> bool:
        """Return True if Node.js is installed (needed to run Claude Code itself)."""
        return shutil.which("node") is not None

    def pull_model(self, model_id: str) -> bool:
        """Run `ollama pull <model_id>`. Returns True on success."""
        self.log(f"  Pulling {model_id} from Ollama library…")
        try:
            result = subprocess.run(
                ["ollama", "pull", model_id],
                timeout=600,
                text=True,
            )
            return result.returncode == 0
        except (subprocess.TimeoutExpired, FileNotFoundError) as exc:
            self.log(f"  [error] ollama pull failed: {exc}")
            return False

    # ── Internals ─────────────────────────────────────────────────────────────

    def _bin_dir(self) -> str:
        system = platform.system()
        if system == "Windows":
            return os.path.join(
                os.environ.get("USERPROFILE", os.path.expanduser("~")),
                "AppData", "Local", "Programs", "claude-setup",
            )
        return os.path.join(os.path.expanduser("~"), ".local", "bin")

    def _wrapper_path(self, bin_dir: str, alias_name: str) -> str:
        if platform.system() == "Windows":
            return os.path.join(bin_dir, f"{alias_name}.cmd")
        return os.path.join(bin_dir, alias_name)

    def _write_wrapper(
        self, path: str, alias_name: str, model_id: str, ollama_url: str
    ):
        if platform.system() == "Windows":
            content = _WIN_WRAPPER.format(
                alias_name=alias_name,
                model_id=model_id,
                ollama_url=ollama_url,
            )
        else:
            content = _UNIX_WRAPPER.format(
                alias_name=alias_name,
                model_id=model_id,
                ollama_url=ollama_url,
            )
        with open(path, "w") as f:
            f.write(content)
        if platform.system() != "Windows":
            st = os.stat(path)
            os.chmod(path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    def _ensure_on_path(self, bin_dir: str):
        """Add bin_dir to PATH in the shell profile if it isn't already there."""
        if platform.system() == "Windows":
            self._ensure_on_path_windows(bin_dir)
            return

        profile = self._shell_profile()
        if not profile:
            self.log(f"  [warn] Could not detect shell profile. Add {bin_dir} to PATH manually.")
            return

        try:
            with open(profile) as f:
                content = f.read()
        except FileNotFoundError:
            content = ""

        if bin_dir in content:
            return

        if profile.endswith("config.fish"):
            snippet = f'\nset -gx PATH "{bin_dir}" $PATH\n'
        else:
            snippet = f'\nexport PATH="{bin_dir}:$PATH"\n'
        with open(profile, "a") as f:
            f.write(snippet)
        self.log(f"  Added {bin_dir} to PATH in {profile}")
        self.log(f"  Run `source {profile}` or open a new terminal to activate.")

    def _ensure_on_path_windows(self, bin_dir: str):
        """Add bin_dir to the user PATH on Windows via setx."""
        try:
            current = os.environ.get("PATH", "")
            if bin_dir.lower() in current.lower():
                return
            subprocess.run(
                ["setx", "PATH", f"{bin_dir};{current}"],
                capture_output=True, timeout=10,
            )
            self.log(f"  Added {bin_dir} to user PATH (restart terminal to apply).")
        except (subprocess.TimeoutExpired, FileNotFoundError):
            self.log(f"  [warn] Could not set PATH automatically. Add {bin_dir} manually.")

    def _shell_profile(self) -> Optional[str]:
        shell = os.environ.get("SHELL", "")
        if "zsh" in shell:
            for p in ("~/.zshrc", "~/.zprofile"):
                path = os.path.expanduser(p)
                if os.path.isfile(path):
                    return path
            return os.path.expanduser("~/.zshrc")
        if "fish" in shell:
            conf = os.path.expanduser("~/.config/fish/config.fish")
            os.makedirs(os.path.dirname(conf), exist_ok=True)
            return conf
        for p in ("~/.bashrc", "~/.bash_profile", "~/.profile"):
            path = os.path.expanduser(p)
            if os.path.isfile(path):
                return path
        return os.path.expanduser("~/.bashrc")

    @staticmethod
    def _extract_value(content: str, key: str) -> Optional[str]:
        """Extract VALUE from lines like  KEY="VALUE"  or  SET KEY=VALUE."""
        import re
        match = re.search(rf'{key}[=:]\s*["\']?([^\s"\'\\]+)', content)
        return match.group(1) if match else None

